In [9]:
import numpy as np
a3 = np.ones([4,5])
print(a3)
print(a3.shape)
d3 = np.random.rand(a3.shape[0], a3.shape[1])
print(d3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(4, 5)
[[0.43006658 0.9809124  0.03624463 0.83635512 0.17284444]
 [0.86714286 0.75580902 0.0870017  0.25715681 0.4514436 ]
 [0.15302336 0.58973108 0.21012944 0.98156175 0.65696872]
 [0.31343543 0.38009487 0.63408816 0.09165329 0.36780319]]
