In [1]:
import numpy as np
import h5py
import matplotlib.pyplot as plt

In [2]:
print(np.dot([1,2,3],[3,4,5]))

26


In [13]:

Y =np.array([[1,1,0]])
m = Y.shape[1]
AL =np.array([[ 0.8,0.9,0.4]])
print(Y)
print(np.log(AL))
print(np.dot(Y,np.log(AL).T))
cost = -1/m*np.sum(np.dot(Y.T,np.log(AL))+np.dot((1-Y).T,np.log(1-AL)))
cost = -1/m*np.sum(np.dot(Y,np.log(AL).T)+np.dot((1-Y),np.log(1-AL).T))



print(cost)

[[1 1 0]]
[[-0.22314355 -0.10536052 -0.91629073]]
[[-0.32850407]]
0.2797765635793422


In [19]:
print(np.array([1,2,3])*np.array([1,2,3]))
print(np.dot(np.array([1,2,3]),np.array([1,2,3])))

[1 4 9]
14


In [24]:
dA = np.array([[-0.41675785, -0.05626683]])
b = np.array([[-0.10414453, -0.01044791]])
print(np.dot(dA,b.T))
print(dA*b)

[[0.04399092]]
[[0.04340305 0.00058787]]
