In [1]:
import numpy as np

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


使用Vectorization 比for循环要快很多

In [14]:
import time

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic = time.time()
c=np.dot(a,b)
toc=time.time()

print(str(1000*(toc-tic))+'ms')
print(c)
c=0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(str(1000*(toc-tic))+'ms')
print(c)

0.5795955657958984ms
249889.70454874253
249.6342658996582ms
249889.70454874236



broadcasting 广播

In [30]:
A = np.array([[1,2,3,4],
             [2,3,4,5],
             [7,8,9,10]])
print(A)
print(A.T)
print('---')
cal = A.sum(axis = 0)
print(A.sum(axis = 0))
print(A.sum(axis = 1))

percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 7  8  9 10]]
[[ 1  2  7]
 [ 2  3  8]
 [ 3  4  9]
 [ 4  5 10]]
---
[10 13 16 19]
[10 14 34]
[[10.         15.38461538 18.75       21.05263158]
 [20.         23.07692308 25.         26.31578947]
 [70.         61.53846154 56.25       52.63157895]]


不要使用rank 1的数组，a和a.T是一样的

In [35]:
a = np.random.randn(5)
print(a)
print(type(a))
print(a.shape)
print(a.T)
print(np.dot(a,a.T))

[-0.08752322  0.48933358 -1.46794611  0.28092875 -0.56136683]
<class 'numpy.ndarray'>
(5,)
[-0.08752322  0.48933358 -1.46794611  0.28092875 -0.56136683]
2.7960271448008576


In [37]:
a = np.random.randn(5,1)# 列向量，1，5行向量
print(a)
print(type(a))
print(a.shape)
print(a.T)
print(np.dot(a,a.T))

[[ 1.52373527]
 [-1.51893059]
 [-0.51856634]
 [ 0.37844688]
 [-0.91932255]]
<class 'numpy.ndarray'>
(5, 1)
[[ 1.52373527 -1.51893059 -0.51856634  0.37844688 -0.91932255]]
[[ 2.32176918 -2.31444811 -0.79015782  0.57665286 -1.4008042 ]
 [-2.31444811  2.30715013  0.78766627 -0.57483454  1.39638715]
 [-0.79015782  0.78766627  0.26891105 -0.19624981  0.47672973]
 [ 0.57665286 -0.57483454 -0.19624981  0.14322204 -0.34791475]
 [-1.4008042   1.39638715  0.47672973 -0.34791475  0.84515396]]
